spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rest-spring-boot
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration


